language: php
php:
  - '7.1'
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libwww-perl
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
script:
  - pwd
  - HEAD http://localhost/test
  - HEAD http://localhost/test.php
  - HEAD http://localhost/www/test
  - HEAD http://localhost/www/test.php
  - HEAD http://127.0.1.1/test
  - HEAD http://127.0.1.1/test.php
  - HEAD http://127.0.1.1/www/test
  - HEAD http://127.0.1.1/www/test.php
  - cat apache-error.log
  - cat apache-access.log
